services:
  - type: web
    name: Flask Backend
    env: python
    region: us-east
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 app:app"